### ISSUE TITLE
install has errors

### ISSUE THREAD

**Issue by blademaster-888** [vampserv/node-poker-stack#5]
has issues with installing and cannot run server. heres the debug file:
[npm-debug.zip](https://github.com/vampserv/node-poker-stack/files/1219315/npm-debug.zip)

below is the runtime error:
![installerror](https://user-images.githubusercontent.com/1754262/29235727-019fdda6-7f45-11e7-87d9-356832c1ffef.png)

**Comment by LeXXik** [comment]
I doubt anyone maintains this any longer. Pity.

**Comment by blademaster-888** [comment]
Ok. I got it to work. For anyone that's interested. heres the instructions how to run it(at least how I did it):
Before you begin uninstall all previous node.js or npm on system and even clear caches or delete node directory just to be safe.

1. download latest node.js(for me its x64 windows so i downloaded 6.11.2) and install it on your system.
2. clone project by typing 
 git clone https://github.com/vampserv/node-poker-stack.git
3. cd node-poker-stack:
4. Install pomelo globally(on windows it installs to C:\Users\[yourusername]\AppData\Roaming\npm\node_modules):
   npm install -g pomelo
5. install game:
  sh npm-install.sh
6. run webserver:
  node web-server/app
7. open another bash and run game server:
  cd game-server
  pomelo start
8. open web browser and load page:
  localhost:3002

9 If everyone went well. try to register and user name and password and u will be able to login.

My result just to prove that it's working:


![image](https://user-images.githubusercontent.com/1754262/29595470-f15e70e2-87fa-11e7-9ae2-fec489bb402a.png)


Have fun learning!

**Comment by delster** [comment]
@telostia Can you post the versions of everything you have; node, npm, python, pomelo, etc? I get errors trying to get this installed on a DigitalOcean droplet and would pay someone to do it.

There's a fork that's trying to keep up with recent socket.io updates here:
https://github.com/EjjE101/node-poker-stack/tree/upgrade_sio

..but I just need this installed, like yesterday.

**Comment by blademaster-888** [comment]
@delster 
you can try changing the package.json file to let pomelo install version 1.20. seems to work.

Heres my current version:

![png](https://user-images.githubusercontent.com/1754262/29698828-c24db75c-899b-11e7-9335-f027e0d50c09.png)


Im using windows 7 on this system.

One thing to note, this game uses gyp so you need to have python 2.7.6 installed to work build properly.

latest pomelo 2.2.5 can be installed and run globally though.

**Comment by LeXXik** [comment]
@delster I have installed the fork you linked on my Ubuntu. Haven't tried this one yet, but I am sure it is same. Had some issues with the installation at first. It was due to the node being new and I had to add an older version. You can check your log, after running the ./npm-install.sh. Not sure what error you have there. If you have the error with gyp failing to build it, then you can try another version of node. I am using nvm for managing my node versions. I switched to version **0.10.21**. After that the installation went fine and I used `node app --harmony` from the game-server folder to start it.

**Comment by delster** [comment]
```
apt-get update
apt-get install build-essential checkinstall
apt-get install libssl-dev
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
nvm install 4.8.4
nvm use 4.8.4
```

(now npm is 2.15.11, node is 4.8.4)

```
npm install pomelo -g
```

(tons of deprecated warnings here, but no error)
pomelo 2.2.5 is now globally installed

```
git clone https://github.com/EjjE101/node-poker-stack.git --branch upgrade_sio --single-branch
cd node-poker-stack
./npm-install.sh
```

(Permission denied)

```
chmod u+x npm-install.sh
./npm-install.sh
```

(both install okay)

![image](https://user-images.githubusercontent.com/3092124/29743455-70121d82-8a60-11e7-8f97-db898f708b54.png)

web-server/app.js will run and show a white screen, but game-server won't. When I was trying it before, I was using all the latest versions of npm, node, pomelo, etc and got a registration screen to pop up but it also wasn't working. When I eventually got around the gyp rebuild issue, I got this:
![image](https://user-images.githubusercontent.com/3092124/29743486-49e9b9d4-8a61-11e7-9645-fab93ad880e4.png)

**Comment by delster** [comment]
Update: I manually went through and uninstalled the dependencies (express, hoyle, pomelo, redis) and manually installed them at the lowest version in the package.json files. I installed pomelo 1.2.x and managed to get both parts running.

It looks fine on the server side, but now the front-end is giving me this:
![image](https://user-images.githubusercontent.com/3092124/29745851-2afaf9a6-8a94-11e7-8323-f3b63a3d25ea.png)

**Comment by blademaster-888** [comment]
@delster when you go and uninstalled the dependencies, it's best you cleared out all the caches including npm and node versions. This happened to me as the different versions was colliding with my build somehow. I'm not sure if it has any effects on the linux side as it did for me in windows, I will install a virtual machine for ubuntu later and will let you know if those setup works for that too. But it is best to start from scratch of all the dependencies including cache files with:  
npm cache clean

Another note is try changing the pomelo ports to something else if you haven't already done it, since you're running on a server there might have been used ports.

**Comment by delster** [comment]
@telostia did the npm cache clean and I'm using screen to open 2 windows. I cycle the droplet's power every time I try to run the game & web servers. Will poke at the ports here shortly. I'd love to get this up and running tonight. You sure you don't want SSH credentials and some $ to sort this out for me?

**Comment by blademaster-888** [comment]
@delster I have to be honest with you I haven't used  linux for a while now so im  not too familiar with environment so It might take a while for me to find my way around with cache locations and paths. That is why I will install a virtual machine to revise my memory.  But if you don't mind I can try winscp and do abit of poking around though I can't guarantee I will succeed. On a side note. was the version of python u used is 2.7.x? if perhaps you're using both 2.7 and 3.x. that might cause problems too. try pomelo start in game-server command instead of node app.  it will use the 2.2.5 version of global pomelo instead

**Comment by delster** [comment]
@telostia what's a good way to pass you credentials? Got an email or something?

**Comment by blademaster-888** [comment]
@delster hold on. I found out that the github fork you had uses higher version of pomelo than this one. I'm getting the same error as you have so I'll be digging out the errors as of now. See if I could get it working and we'll proceed further.

**Comment by blademaster-888** [comment]
@delster you mentioned you had this fork installed before? what was the version of npm,node were you using?

**Comment by delster** [comment]
I had the latest npm, latest node 6.x, latest python 2.7.x, and everything else was installed globally with 
```
npm install [thing] -g
```
so latest versions of those as well (screen, pomelo, etc)

**Comment by delster** [comment]
Related?
https://github.com/socketio/socket.io/issues/1046

**Comment by LeXXik** [comment]
@delster 
Hmm, somehow I don't have the XMLHttpRequest error. Here is my output of running `pomelo start`:

![image](https://user-images.githubusercontent.com/5677782/29748532-3fb3820c-8b4b-11e7-8146-22d265f76c6b.png)

![image](https://user-images.githubusercontent.com/5677782/29748591-2968f800-8b4c-11e7-9cc7-c68c12c4cb13.png)

![image](https://user-images.githubusercontent.com/5677782/29748657-18444ede-8b4d-11e7-879e-b44e786931d3.png)

**Comment by blademaster-888** [comment]
@delster I think I know what the problem was. when you do a npm install -d command when changing nodes and doing it again it somehow corrupts the whole node_modules folder(or w/e happened in there...)

what I did to solve it was to build using old version of node.

1. do
 nvm use 0.10.21(nvm install 0.10.21 64     to install it if you haven't got it) with the following settings in the package.json file:

![image](https://user-images.githubusercontent.com/1754262/29749409-03e1df44-8b6e-11e7-96c4-2e899f522d94.png)

2. change to another version of node with:
nvm use 4.8.4(maybe higher works I dunno but try this)
now go to game-server folder and run:
node app

![image](https://user-images.githubusercontent.com/1754262/29749422-7e075f06-8b6e-11e7-8c6e-f489968c3c90.png)


What a pain in the ass this was. if you get errors chances are your node_modules folder got corrupted(easiest to tell is that you have alot more modules in it than you declared...)

So delete the node_modules folder before you do an npm install -d or npm-install.sh. That's my two cents :)

EDIT: maybe you don't need to change to version 4.8.4 but for me I use windows and --harmony doesn't seem to work. version 4.8.4 has the feature built in(something to do with ECMAScript 6)

**Comment by delster** [comment]
I see (upgrade_sio) in your screenshot so I'll try that branch again. I destroyed the droplet I was working on and spun up a new one running Ubuntu 16.04.3 x64

```
apt-get update
apt-get install build-essential checkinstall
apt-get install libssl-dev
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
```
[close and open connection]
```
nvm install 0.10.21
nvm use 0.10.21
```
[node v0.10.21, npm v1.3.11]
```
git clone https://github.com/EjjE101/node-poker-stack.git --branch upgrade_sio --single-branch
cd node-poker-stack
cd game-server
pico -w package.json
```
[Installed Python 2.7.12 and changed dependencies to the screenshot above; pomelo, crc, hoyle, node-uuid, pomelo-logger, redis]
```
cd ..
chmod u+x npm-install.sh
./npm-install.sh
```
[Both installed fine.]
![image](https://user-images.githubusercontent.com/3092124/29751493-04c4552e-8b1c-11e7-99c4-26518e81433b.png)

```
nvm install 4.8.4 64
nvm use 4.8.4
```
[node v4.8.4, npm v2.15.11]
Go into game-server and "node app"..
![image](https://user-images.githubusercontent.com/3092124/29751494-0d595ca2-8b1c-11e7-9498-11366e525db9.png)


Still no joy.

**Comment by delster** [comment]
Had no luck with "pomelo start" either so I installed the latest version globally using [node v4.8.4, npm v2.15.11] and managed to get it running again:
![image](https://user-images.githubusercontent.com/3092124/29754452-722f1928-8b53-11e7-8030-c44a0e25ed15.png)

but having the CORS issue. Still have to play with the ports or something, I guess.

**Comment by blademaster-888** [comment]
@delster I don't think the new fork is without errors so you might have to go into the code and fix it yourself. 

When I tried the following settings:

[package.json]

"dependencies": {
    "pomelo": "^2.2.5",
    "crc": "0.2.0",
    "hoyle": "^0.2.2",
    "node-uuid": "^1.4.1",
    "pomelo-logger": "^0.1.6",
    "redis": "^2.7.1"
  }

and build using node 4.8.4 globally(reason globally is so that I could use command pomelo list to see whats being running)
![image](https://user-images.githubusercontent.com/1754262/29754709-5fddf732-8bce-11e7-805e-0eea6621d4ea.png)

Although I see some errors, it doesnt affect the gameplay.
![image](https://user-images.githubusercontent.com/1754262/29754718-806f0d24-8bce-11e7-82a2-18e52cb1a547.png)

Heres the SS during play
![image](https://user-images.githubusercontent.com/1754262/29754724-a4ca2fbe-8bce-11e7-94fa-ba0578241525.png)

You can edit the index.html file and change the socket.io.js to something like latest
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script> 
for example, to me i noticed a boost in reaction time but it's just my feelling.

Good luck with code! I will be making my own poker type server(and something like unity or phaser js client for mobile devices whichever is more feasible) based on this code soon. Hopefully nothing major goes wrong, if not i could fall back to just using without pomelo and using just redis itself
like how this guy did it 
https://github.com/floatinghotpot/casino-server. So if all goes well, I could come back and adjust this codebase to have mongodb or mysql database and with a proper client for the masses.(big plans... so hopefully things go smooth :) )

**Comment by delster** [comment]
Changing the socket.io script location in index.html did nothing. Still getting the "No 'Access-Control-Allow-Origin' header is present on the requested resource." error on the front-end. I just need a web-based poker server running in the next couple days, tbh.

**Comment by blademaster-888** [comment]
@delster Not sure about that error but It doesn't sound like it from the game itself. are you running local host or over the net?

**Comment by delster** [comment]
I'm trying to get this running on a DigitalOcean droplet.

**Comment by blademaster-888** [comment]
@delster wouldn't it be more stable to run this main branch than the fork branch?

**Comment by delster** [comment]
I'm willing to try to run this one, but your screenshot had the other so I figured stick with what works.

**Comment by blademaster-888** [comment]
No. what i meant was . where is the client running on? from server or from another device

**Comment by blademaster-888** [comment]
the same theory applies to this branch too. I tried both, works flawlessly

**Comment by telostia** [comment]
You have discord?

**Comment by delster** [comment]
From the server. I use "screen" which lets you open multiple terminal sessions in the same window. I SSH in, run the game-server app with "pomelo start", use screen to switch to another terminal session, run the web-server app with "node app", then access the front-end with [droplet-ip-address]:3002 in my browser. I do have Discord, yes.

**Comment by telostia** [comment]
If there was a free trial, I would have tried it myself.

**Comment by telostia** [comment]
make a channel in discord, I will connect to it.

**Comment by delster** [comment]
https://discord.gg/9vVBHV

**Comment by telostia** [comment]
send the details to my email

**Comment by telostia** [comment]
k delete the message now

**Comment by telostia** [comment]
blademaster on discord.

**Comment by LeXXik** [comment]
@telostia by the way, those errors in the console, which as you mentioned do not affect the gameplay, are caused by `game-server/node-modules/pomelo/lib/sioconnector.js`, which is sending `socket.io` some options, that are no longer supported. The list of supported options can be found [here](https://github.com/socketio/engine.io#methods-1). You can safely comment out those options to remove the console errors.

EDIT:
Looking forward for mongodb and redis integration :)

**Comment by LeXXik** [comment]
Another point I wanted to mention regarding using `pomelo start` vs `node app.js --harmony` is that `pomelo start` is preferred.

![image](https://user-images.githubusercontent.com/5677782/29762845-16568234-8c03-11e7-97b8-6a5944a6311d.png)

From pomelo wiki:
> It can be seen from the figure, the process "pomelo start" will spawn a child process, which execs "node app.js env = development", and then the child process will spawn a series of child processes, all the child processes exec same orignal file "app.js", but with more parameters, such as id, serverType, port and so on.

**Comment by blademaster-888** [comment]
@LeXXik  thanks for the heads up. Are you one of pomelo's developer? I see you have updated the pomelo-framework overview. 
--harmony doesn't work in my case so that's no good.
About the socketio I see because the fork used higher version which then made the errors pop up. Does that mean I have to build a pomelo version of 2.2.5 and manually comment it out?

**Comment by blademaster-888** [comment]
instead of building, I went and comment like this:

//sio.set('path', '/socket.io');
  sio.set('transports', this.opts.transports);
  //sio.set('close timeout', this.closeTimeout);
  //sio.set('heartbeat timeout', this.heartbeatTimeout);
  //sio.set('heartbeat interval', this.heartbeatInterval);
  //sio.set('heartbeats', this.heartbeats);
  //sio.set('log level', 1);

which results as:

![image](https://user-images.githubusercontent.com/1754262/29764042-09c712de-8c19-11e7-8abf-fa18519e841c.png)

EDIT: Which would mean that pomelo doesn't use the latest socketio?

**Comment by LeXXik** [comment]
@telostia 
Nope, I am not related to pomelo project. I only made some minor changes to the wiki pages.

You can leave `heartbeat timeout` and `heartbeat interval` uncommented. Pomelo will convert them to `pingTimeout` and `pingInterval` respectively, which are supported.

And regarding your question, I am not sure what would be the best way to proceed. Ideally, NetEase team should update their framework of course. However, they probably no longer support it, or not very actively.

EDIT: And no, it doesn't use the latest socket.io. I believe it uses v1.7.2.
